name: Forwardport changes to main
on:
  push:
    branches:
      - v/*
jobs:
  forwardport:
    uses: ./.github/workflows/backport-workflow.yml
    with:
      label-to-check-for: '["forwardport to snapshot"]'
      target-branches: '["main"]'
    secrets: inherit
